name: 'Telewire'
description: 'Connect your GitHub Repo to Telegram'
author: 'athul'
inputs: 
  chat:
    description: 'Chat to send: chat id or @channel_name'
    required: true
  token:
    description: 'Telegram Bot token'
    required: true
  status:
    description: 'Job status'
    required: true
  stargazers:
    description: 'Get Stars of the Repo'
    default: ${{ github.event.repository.stargazers_count }}
  forkers:
    description: 'Number of Forks'
    default: ${{ github.event.repository.forks_count }}
  iu_title: 
    description: 'Issue Title'
    default: ${{ github.event.issue.title }}
  iu_num:
    description: 'Issue Number'
    default: ${{ github.event.issue.number }}
  iu_actor: 
    description: 'Issue Triggerer'
    default: ${{ github.event.issue.user.login }}
  iu_body:
    description: 'Issue Body'
    default: ${{ github.event.issue.body }}
  iu_com:
    description: 'Issue Comment'
    default: ${{github.event.comment.body}}
  pr_state:
    description: 'State of the PR'
    default: ${{ github.event.action }}
  pr_num:
    description: 'PR Number'
    default: ${{ github.event.number }}
  pr_title:
    description: 'Title of the PR'
    default: ${{ github.event.pull_request.title }}
  pr_body:
    description: 'Body/Contents of the PR'
    default: ${{ github.event.pull_request.body }}
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'repeat'  
  color: 'green'